root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  general/overview/architecture: general/overview/introduction.md
  general/overview/tokenomics: general/overview/introduction.md
