root: ./

structure:
  readme: README.md
  summary: SUMMARY.md

redirects:
  general/overview/introduction: general/overview.md
  general/overview/architecture: general/overview.md
  general/overview/tokenomics: general/overview.md
  protocol/strategy: protocol/overview.md
  protocol/infrastructure: protocol/overview.md
  protocol/trading-infrastructure: protocol/overview.md
